### ISSUE TITLE
是否会考虑支持课堂评价

### ISSUE THREAD

**Issue by sakuraMY** [Well2333/Auto-evaluate-scripts-for-HMU#1]
目前在同是乘方教务上面运行期末评正常
![image](https://github.com/Well2333/Auto-evaluate-scripts-for-HMU/assets/67968412/e8334f73-7fe3-4b7f-a0c3-a9c2ecded530)

![image](https://github.com/Well2333/Auto-evaluate-scripts-for-HMU/assets/67968412/83ee30b3-da18-4224-908c-0bfc2583fc97)

**Comment by Well2333** [comment]
由于我这里没有课堂评价，没法进行css抓取和测试，暂时不考虑，如果量非常大或者需求较多的情况我再酌情加入
